#!/bin/bash
python train_w_mode_switch_sgpu.py \
	--data_dir=data_inC_bar_pad/train/Electronic\
	--val_data_dir=data_inC_bar_pad/val/Electronic\
	--big_frame_size=16 \
	--frame_size=4 \
	--rnn_type=GRU \
	--dim=512 \
	--n_rnn=1 \
	--batch_size=256 \
	--optimizer=adam \
	--num_gpus=1\
    --if_cond=cond\
    --mode_choice=bar_note\
	--piano_dim=197\
	--note_channel=130\
	--rhythm_channel=16\
	--seq_len=128\
	--chord_channel=49\
	--drop_out=0.5\
	--alpha1=0.4\
	--alpha2=0.3